
// USERS
GET http://localhost:5000/users

###

POST http://localhost:5000/users/register/ 
content-type: application/json

{
   "email": "eric@gmail.com",
   "password": "test123",
   "passwordCheck": "test123",
   "displayName": "Eric Newcomer"
}

###

POST http://localhost:5000/users/login/ 
content-type: application/json

{
   "email": "eric@gmail.com",
   "password": "test123"
}

###

// OPPORTUNITIES
GET http://localhost:5000/opportunities

###

POST http://localhost:5000/opportunities/add/ 
content-type: application/json

{
   "opportunityTitle": "Store Clerk",
   "companyName": "Ralph's",
   "description": "You will be a store clerk!"
}